server:
  port: 8001

libra:
  log:
    kafka: false
    trace: false
    level: error,info
  scanner: 
    open: true
    
jwt:
  secret: abcdefg
  expiration: 82800
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libra_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      type: BATCH
    producer:
      batchSize: 500
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: com.libra.core.logger.serizlizer.FastjsonKafkaSerializer
    consumer:
      group-id: commonLogList
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: com.libra.core.logger.serizlizer.FastjsonKafkaDeserializer
      auto-offset-reset: earliest
      maxPollRecords: 500

mybatis-plus:
  typeAliasesPackage: com.libra.cloud.system.entity

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
    lease-renewal-interval-in-seconds: 5       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 10  #重新刷新服务地址的时间

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 300  #创建连接的超时时间 单位：毫秒
        readTimeout: 3000    #处理请求的超时时间 单位：毫秒
        errorDecoder: com.libra.core.feign.FeignErrorDecoder
        requestInterceptors:
        - com.libra.core.feign.FeignHeaderProcessInterceptor

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE #为了RosesFeignHeaderProcessInterceptor
          thread:
            timeoutInMilliseconds: 2000
